import React from 'react';
import { Download, Table, Calendar, Tag, ShieldAlert } from 'lucide-react';
import type { ForecastResult } from '../types/forecast';
import { formatDemand } from '../utils/formatDemand';

interface ForecastTableProps {
  results: ForecastResult[];
}

export const ForecastTable: React.FC<ForecastTableProps> = ({ results }) => {
  if (results.length === 0) return null;

  // Find Peak and Trough to add badges
  let maxVal = -Infinity;
  let minVal = Infinity;
  
  results.forEach((r) => {
    if (r.predictedDemand > maxVal) maxVal = r.predictedDemand;
    if (r.predictedDemand < minVal) minVal = r.predictedDemand;
  });

  const getDayDetails = (dateStr: string) => {
    const parts = dateStr.split('-');
    const dateObj = new Date(Number(parts[0]), Number(parts[1]) - 1, Number(parts[2]));
    const weekdayName = dateObj.toLocaleDateString('en-US', { weekday: 'long' });
    const weekdayShort = dateObj.toLocaleDateString('en-US', { weekday: 'short' });
    const isWeekend = dateObj.getDay() === 0 || dateObj.getDay() === 6;
    
    return { weekdayName, weekdayShort, isWeekend };
  };

  const formatReadableDate = (dateStr: string) => {
    const parts = dateStr.split('-');
    const dateObj = new Date(Number(parts[0]), Number(parts[1]) - 1, Number(parts[2]));
    return dateObj.toLocaleDateString('en-US', { month: 'short', day: '2-digit', year: 'numeric' });
  };

  // CSV Exporter Action
  const handleExportCSV = () => {
    const headers = [
      'Date', 
      'Day of Week', 
      'Discount (%)', 
      'Promotion Active', 
      'Epidemic Active', 
      'Predicted Demand',
      'Lower 95% CI',
      'Upper 95% CI'
    ];
    const rows = results.map((item) => {
      const details = getDayDetails(item.date);
      return [
        item.date,
        details.weekdayName,
        item.discount,
        item.promotion === 1 ? 'Yes' : 'No',
        item.epidemic === 1 ? 'Yes' : 'No',
        item.predictedDemand.toFixed(2),
        item.lower95.toFixed(2),
        item.upper95.toFixed(2),
      ];
    });

    const csvContent = [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);

    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', `demand_forecast_${results[0].date}_to_${results[results.length - 1].date}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div style={containerStyles} className="fade-slide-up">
      {/* Title Header with Export Action */}
      <div style={headerStyles}>
        <div>
          <h3 className="card-title" style={{ margin: 0 }}>
            <Table size={18} color="var(--accent-primary)" />
            Daily Prediction Records
          </h3>
          <p className="card-subtitle" style={{ margin: 0, marginTop: '2px' }}>
            Scenario records generated by the forecasting model.
          </p>
        </div>
        <button
          onClick={handleExportCSV}
          className="btn-secondary"
          style={exportBtnStyles}
          title="Download forecast data as CSV"
          aria-label="Export Data as CSV"
        >
          <Download size={14} />
          <span>Export CSV</span>
        </button>
      </div>

      {/* Grid of elegant cards instead of a boring table */}
      <div style={cardsListStyles}>
        {results.map((item, index) => {
          const isPeak = results.length > 1 && item.predictedDemand === maxVal;
          const isLowest = results.length > 1 && item.predictedDemand === minVal;
          const dayMeta = getDayDetails(item.date);

          return (
            <div
              key={item.date}
              className="prediction-record-card fade-slide-up"
              style={{
                ...recordCardStyles,
                animationDelay: `${index * 35}ms`,
                borderLeft: isPeak 
                  ? '4px solid var(--color-warning)' 
                  : isLowest 
                  ? '4px solid var(--color-info)' 
                  : '1px solid var(--border-color)',
              }}
            >
              {/* Column 1: Date & Weekday Badge */}
              <div style={colDateStyles}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                  <Calendar size={14} color="var(--accent-secondary)" />
                  <span style={dateTextStyles}>{formatReadableDate(item.date)}</span>
                </div>
                <div>
                  {dayMeta.isWeekend ? (
                    <span className="badge-weekend" style={weekendBadgeStyles}>
                      {dayMeta.weekdayName}
                    </span>
                  ) : (
                    <span style={weekdayNeutralStyles}>{dayMeta.weekdayName}</span>
                  )}
                </div>
              </div>

              {/* Column 2: Applied Operating Conditions */}
              <div style={colConditionsStyles}>
                {/* Discount */}
                <div style={conditionPillStyles} title="Discount value">
                  <Tag size={11} color="var(--accent-primary)" />
                  <span>{item.discount}% Off</span>
                </div>

                {/* Promo Badge */}
                {item.promotion === 1 ? (
                  <div style={promoActiveStyles} title="Active marketing campaign">
                    <span style={activeDotStyles}></span>
                    <span>Promo Active</span>
                  </div>
                ) : (
                  <div style={promoInactiveStyles}>
                    <span>No Promo</span>
                  </div>
                )}

                {/* Epidemic Warning */}
                {item.epidemic === 1 ? (
                  <div style={epidemicActiveStyles} title="Epidemic containment measures">
                    <ShieldAlert size={12} />
                    <span>Epidemic Alert</span>
                  </div>
                ) : (
                  <div style={epidemicInactiveStyles}>
                    <span>Normal Conditions</span>
                  </div>
                )}
              </div>

              {/* Column 3: Predictions and Confidence Intervals */}
              <div style={colPredictionsStyles}>
                <div style={demandWrapperStyles}>
                  {isPeak && <span className="badge badge-peak" style={{ padding: '1px 6px', fontSize: '9px' }}>Peak</span>}
                  {isLowest && <span className="badge badge-lowest" style={{ padding: '1px 6px', fontSize: '9px' }}>Lowest</span>}
                  <span style={predictionValStyles}>{formatDemand(item.predictedDemand)}</span>
                </div>
                <div style={ciRangeStyles}>
                  <span>95% CI:</span>
                  <strong>{formatDemand(item.lower95)} – {formatDemand(item.upper95)}</strong>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};

// Layout configurations
const containerStyles: React.CSSProperties = {
  width: '100%',
};

const headerStyles: React.CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'space-between',
  marginBottom: '1.25rem',
  gap: '1rem',
};

const exportBtnStyles: React.CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  gap: '0.375rem',
  padding: '0.4rem 0.75rem',
  fontSize: '0.775rem',
};

const cardsListStyles: React.CSSProperties = {
  display: 'flex',
  flexDirection: 'column',
  gap: '0.75rem',
  width: '100%',
};

const recordCardStyles: React.CSSProperties = {
  display: 'flex',
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-between',
  padding: '1rem 1.25rem',
  backgroundColor: 'var(--bg-card)',
  borderRadius: '16px',
  border: '1px solid var(--border-color)',
  boxShadow: 'var(--shadow-card)',
  transition: 'transform var(--transition-fast), border-color var(--transition-fast), box-shadow var(--transition-fast)',
  gap: '1.5rem',
};

// Column styles
const colDateStyles: React.CSSProperties = {
  display: 'flex',
  flexDirection: 'column',
  gap: '0.375rem',
  minWidth: '150px',
  textAlign: 'left',
};

const dateTextStyles: React.CSSProperties = {
  fontSize: '0.85rem',
  fontWeight: 700,
  color: 'var(--text-primary)',
};

const weekdayNeutralStyles: React.CSSProperties = {
  fontSize: '0.75rem',
  fontWeight: 600,
  color: 'var(--text-secondary)',
  paddingLeft: '1.25rem',
};

const colConditionsStyles: React.CSSProperties = {
  display: 'flex',
  flexWrap: 'wrap',
  gap: '0.5rem',
  flex: '1',
  justifyContent: 'flex-start',
  alignItems: 'center',
};

const colPredictionsStyles: React.CSSProperties = {
  display: 'flex',
  flexDirection: 'column',
  alignItems: 'flex-end',
  gap: '0.25rem',
  minWidth: '180px',
};

const demandWrapperStyles: React.CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  gap: '0.5rem',
};

const predictionValStyles: React.CSSProperties = {
  fontSize: '1.35rem',
  fontWeight: 800,
  color: 'var(--text-primary)',
  letterSpacing: '-0.01em',
};

const ciRangeStyles: React.CSSProperties = {
  fontSize: '0.725rem',
  color: 'var(--text-secondary)',
  display: 'flex',
  gap: '0.25rem',
};

// Badges styles
const weekendBadgeStyles: React.CSSProperties = {
  fontSize: '0.7rem',
  fontWeight: 700,
  backgroundColor: '#EAF4FF',
  color: '#3B82F6',
  border: '1px solid #CDE3FF',
  padding: '1px 8px',
  borderRadius: '6px',
  display: 'inline-block',
  marginLeft: '1.25rem',
};

const conditionPillStyles: React.CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  gap: '0.375rem',
  padding: '3px 8px',
  backgroundColor: 'rgba(83, 109, 254, 0.05)',
  border: '1px solid rgba(83, 109, 254, 0.1)',
  borderRadius: '8px',
  fontSize: '0.75rem',
  fontWeight: 600,
  color: 'var(--text-primary)',
};

const promoActiveStyles: React.CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  gap: '0.375rem',
  padding: '3px 8px',
  backgroundColor: 'var(--color-success-bg)',
  border: '1px solid rgba(16, 185, 129, 0.15)',
  borderRadius: '8px',
  fontSize: '0.75rem',
  fontWeight: 600,
  color: 'var(--color-success)',
};

const promoInactiveStyles: React.CSSProperties = {
  padding: '3px 8px',
  border: '1px solid var(--border-color)',
  borderRadius: '8px',
  fontSize: '0.725rem',
  fontWeight: 500,
  color: 'var(--text-secondary)',
};

const activeDotStyles: React.CSSProperties = {
  width: '5px',
  height: '5px',
  borderRadius: '50%',
  backgroundColor: 'var(--color-success)',
};

const epidemicActiveStyles: React.CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  gap: '0.375rem',
  padding: '3px 8px',
  backgroundColor: 'var(--color-danger-bg)',
  border: '1px solid rgba(239, 68, 68, 0.15)',
  borderRadius: '8px',
  fontSize: '0.75rem',
  fontWeight: 600,
  color: 'var(--color-danger)',
};

const epidemicInactiveStyles: React.CSSProperties = {
  padding: '3px 8px',
  border: '1px solid var(--border-color)',
  borderRadius: '8px',
  fontSize: '0.725rem',
  fontWeight: 500,
  color: 'var(--text-secondary)',
};

// Add responsive overrides inside document head and card hover effects
const cardStyleSheet = document.createElement('style');
cardStyleSheet.textContent = `
  .prediction-record-card:hover {
    transform: translateY(-2px);
    border-color: rgba(83, 109, 254, 0.2) !important;
    box-shadow: var(--shadow-hover) !important;
  }
  @media (max-width: 768px) {
    .prediction-record-card {
      flex-direction: column !important;
      align-items: flex-start !important;
      gap: 0.875rem !important;
      padding: 1.25rem !important;
    }
    .prediction-record-card div {
      width: 100%;
      text-align: left;
    }
    .prediction-record-card > div:last-child {
      align-items: flex-start !important;
      border-top: 1px solid var(--border-color);
      padding-top: 0.75rem;
      margin-top: 0.25rem;
    }
    .badge-weekend {
      margin-left: 0 !important;
    }
    .prediction-record-card span {
      padding-left: 0 !important;
    }
  }
`;
document.head.appendChild(cardStyleSheet);

export default ForecastTable;
